const CUESTIONARIO = [
  {
    id: 'perspectiva',
    title: '1. AMAREA DESDE TU PERSPECTIVA',
    questions: [
      { id: 'q1', text: `¿Qué es AMAREA para ti?` },
      { id: 'q2', text: `Si tuvieras que explicárselo a alguien que nunca ha escuchado hablar de AMAREA, ¿qué le dirías?` },
      { id: 'q3', text: `Completa la frase: AMAREA es...` },
      { id: 'q4', text: `Completa la frase: AMAREA no es...` },
      { id: 'q5', text: `¿Por qué existe AMAREA?` },
      { id: 'q6', text: `¿Qué necesidad, deseo o inquietud dio origen a AMAREA?` },
      { id: 'q7', text: `¿Qué creen que estaban intentando hacer cuando comenzaron?` },
      { id: 'q8', text: `¿Qué creen que están haciendo realmente ahora?` },
      { id: 'q9', text: `¿Qué ha cambiado desde que comenzó AMAREA?` },
      { id: 'q10', text: `¿Qué permanece exactamente igual?` },
      { id: 'q11', text: `¿Qué significa para ti pertenecer a AMAREA?` },
      { id: 'q12', text: `¿Qué perderías personalmente si AMAREA dejara de existir?` },
      { id: 'q13', text: `¿Qué perdería el entorno de AMAREA si dejara de existir?` },
      { id: 'q14', text: `¿Qué crees que AMAREA aporta que actualmente hace falta?` },
      { id: 'q15', text: `¿Qué problema, vacío o posibilidad está ocupando AMAREA?` },
      { id: 'q16', text: `¿Qué hace AMAREA que no podría hacer una persona individual?` },
      { id: 'q17', text: `¿Qué hace AMAREA que no podría hacer una productora convencional?` },
      { id: 'q18', text: `¿Qué parte de AMAREA consideras más importante?` },
      { id: 'q19', text: `¿Qué parte consideras más prescindible?` },
      { id: 'q20', text: `¿Qué crees que todavía no han entendido ustedes mismos sobre AMAREA?` }
    ]
  },
  {
    id: 'experiencia',
    title: '2. LA EXPERIENCIA QUE CONSTRUYEN',
    questions: [
      { id: 'q21', text: `Cuando alguien asiste a una experiencia de AMAREA, ¿qué quieres que le ocurra?` },
      { id: 'q22', text: `¿Qué quieres que sienta?` },
      { id: 'q23', text: `¿Qué quieres que piense?` },
      { id: 'q24', text: `¿Qué quieres que recuerde?` },
      { id: 'q25', text: `¿Qué quieres que cuente después?` },
      { id: 'q26', text: `¿Qué momento de una experiencia AMAREA consideras más importante?` },
      { id: 'q27', text: `¿Qué elementos hacen que una experiencia se sienta verdaderamente AMAREA?` },
      { id: 'q28', text: `¿Qué elementos pueden cambiar de un evento a otro sin afectar la identidad?` },
      { id: 'q29', text: `¿Qué elementos no deberían cambiar nunca?` },
      { id: 'q30', text: `¿Qué cosas hacen que una experiencia deje de sentirse AMAREA?` },
      { id: 'q31', text: `¿Qué diferencia existe entre una fiesta cualquiera y una experiencia AMAREA?` },
      { id: 'q32', text: `¿Qué diferencia existe entre contratar a AMAREA y simplemente contratar una productora?` },
      { id: 'q33', text: `¿Qué parte de la experiencia pertenece a la música?` },
      { id: 'q34', text: `¿Qué parte pertenece al espacio?` },
      { id: 'q35', text: `¿Qué parte pertenece a la gente?` },
      { id: 'q36', text: `¿Qué parte pertenece a la producción?` },
      { id: 'q37', text: `¿Qué parte pertenece a la estética?` },
      { id: 'q38', text: `¿Qué parte pertenece a la sorpresa o a lo inesperado?` },
      { id: 'q39', text: `¿Qué parte pertenece al contexto de Los Cabos/Baja California Sur?` },
      { id: 'q40', text: `Si tuvieras que describir una experiencia AMAREA perfecta de principio a fin, ¿cómo sería?` }
    ]
  },
  {
    id: 'musica',
    title: '3. MÚSICA, ARTE Y CURADURÍA',
    questions: [
      { id: 'q41', text: `¿Qué papel ocupa la música dentro de AMAREA?` },
      { id: 'q42', text: `¿Qué papel ocupa el arte?` },
      { id: 'q43', text: `¿Qué papel ocupa la tecnología?` },
      { id: 'q44', text: `¿Qué papel ocupa la producción audiovisual?` },
      { id: 'q45', text: `¿Qué papel ocupa el espacio?` },
      { id: 'q46', text: `¿Qué papel ocupa la programación de artistas?` },
      { id: 'q47', text: `¿Qué características tiene un artista que encaja naturalmente en AMAREA?` },
      { id: 'q48', text: `¿Qué características tendría un artista excelente que, aun así, no encajaría en AMAREA?` },
      { id: 'q49', text: `¿Cómo describirías el sonido de AMAREA?` },
      { id: 'q50', text: `¿Cómo describirías la estética artística de AMAREA?` },
      { id: 'q51', text: `¿Qué géneros musicales pertenecen naturalmente al universo AMAREA?` },
      { id: 'q52', text: `¿Qué géneros podrían entrar aunque no sean habituales?` },
      { id: 'q53', text: `¿Qué géneros definitivamente no corresponden?` },
      { id: 'q54', text: `¿Qué buscan realmente cuando eligen un artista?` },
      { id: 'q55', text: `¿Qué valoran más: trayectoria, talento, propuesta, personalidad, energía, comunidad, exclusividad u otra cosa?` },
      { id: 'q56', text: `¿Cómo deciden actualmente qué artistas participan?` },
      { id: 'q57', text: `¿Cómo deciden actualmente qué espacios utilizar?` },
      { id: 'q58', text: `¿Cómo deciden actualmente qué concepto desarrollar?` },
      { id: 'q59', text: `¿Quién tiene mayor influencia sobre las decisiones creativas?` },
      { id: 'q60', text: `¿Qué criterio debería existir para determinar si algo es o no AMAREA?` }
    ]
  },
  {
    id: 'identidad',
    title: '4. IDENTIDAD Y POSICIONAMIENTO',
    questions: [
      { id: 'q61', text: `¿Cómo quieres que AMAREA sea percibida?` },
      { id: 'q62', text: `¿Cómo crees que actualmente es percibida?` },
      { id: 'q63', text: `¿Existe una diferencia entre ambas cosas? ¿Cuál?` },
      { id: 'q64', text: `¿Qué palabras describen correctamente a AMAREA?` },
      { id: 'q65', text: `¿Qué palabras NO deberían utilizarse para describirla?` },
      { id: 'q66', text: `¿Qué marcas, colectivos, artistas, espacios o proyectos consideran cercanos a AMAREA?` },
      { id: 'q67', text: `¿Cuáles consideran referentes?` },
      { id: 'q68', text: `¿Cuáles admiran aunque no quieran parecerse a ellos?` },
      { id: 'q69', text: `¿De quién quieren diferenciarse?` },
      { id: 'q70', text: `¿Qué hace que AMAREA sea reconocible?` },
      { id: 'q71', text: `Si quitaras el nombre AMAREA de una experiencia, ¿qué elementos permitirían reconocerla?` },
      { id: 'q72', text: `¿Qué significa el nombre AMAREA para ti?` },
      { id: 'q73', text: `¿Qué historia hay detrás del nombre?` },
      { id: 'q74', text: `¿Qué debería transmitir visualmente la marca?` },
      { id: 'q75', text: `¿Qué debería transmitir verbalmente?` },
      { id: 'q76', text: `Si AMAREA fuera una persona, ¿cómo sería?` },
      { id: 'q77', text: `¿Cómo hablaría?` },
      { id: 'q78', text: `¿Cómo se vestiría?` },
      { id: 'q79', text: `¿Qué lugares frecuentaría?` },
      { id: 'q80', text: `¿Qué jamás haría?` }
    ]
  },
  {
    id: 'publico',
    title: '5. LAS PERSONAS QUE QUIEREN ATRAER',
    questions: [
      { id: 'q81', text: `¿Para quién existe AMAREA?` },
      { id: 'q82', text: `Describe a la persona que más naturalmente conecta con AMAREA.` },
      { id: 'q83', text: `¿Qué edad tiene aproximadamente?` },
      { id: 'q84', text: `¿De dónde viene?` },
      { id: 'q85', text: `¿Qué música escucha?` },
      { id: 'q86', text: `¿Qué otros eventos o espacios frecuenta?` },
      { id: 'q87', text: `¿Qué busca cuando sale?` },
      { id: 'q88', text: `¿Qué rechaza?` },
      { id: 'q89', text: `¿Qué hace que alguien decida asistir a AMAREA?` },
      { id: 'q90', text: `¿Qué hace que regrese?` },
      { id: 'q91', text: `¿Qué hace que invite a otras personas?` },
      { id: 'q92', text: `¿Quién definitivamente no es el público de AMAREA?` },
      { id: 'q93', text: `¿Quieren atraer principalmente público local, visitantes o ambos?` },
      { id: 'q94', text: `¿Qué relación quieren tener con artistas, creativos y productores locales?` },
      { id: 'q95', text: `¿Qué relación quieren tener con visitantes nacionales e internacionales?` },
      { id: 'q96', text: `¿Qué tipo de comunidad quieren construir alrededor de AMAREA?` },
      { id: 'q97', text: `¿Esa comunidad debería existir también cuando no hay eventos?` },
      { id: 'q98', text: `¿Qué podría ofrecer AMAREA entre eventos?` },
      { id: 'q99', text: `¿Qué relación debería existir entre AMAREA y el territorio donde opera?` },
      { id: 'q100', text: `¿Qué creen que busca realmente la gente cuando llega a una experiencia AMAREA?` }
    ]
  },
  {
    id: 'negocio',
    title: '6. EL NEGOCIO QUE PODRÍA EXISTIR',
    questions: [
      { id: 'q101', text: `¿Consideras que AMAREA es un negocio?` },
      { id: 'q102', text: `Si sí, ¿qué vende realmente?` },
      { id: 'q103', text: `Si no, ¿qué es y por qué?` },
      { id: 'q104', text: `¿Qué creen que está pagando realmente una persona cuando compra un boleto para AMAREA?` },
      { id: 'q105', text: `¿Qué otras cosas podría vender AMAREA además de boletos?` },
      { id: 'q106', text: `¿Qué servicios podría ofrecer?` },
      { id: 'q107', text: `¿Qué experiencias podría producir?` },
      { id: 'q108', text: `¿Qué relación podría tener con marcas?` },
      { id: 'q109', text: `¿Qué relación podría tener con venues?` },
      { id: 'q110', text: `¿Qué relación podría tener con hoteles?` },
      { id: 'q111', text: `¿Qué relación podría tener con artistas?` },
      { id: 'q112', text: `¿Qué relación podría tener con otras productoras?` },
      { id: 'q113', text: `¿Qué relación podría tener con instituciones culturales?` },
      { id: 'q114', text: `¿Qué otras fuentes de ingresos imaginan?` },
      { id: 'q115', text: `¿Qué cosas no quieren convertir en negocio?` },
      { id: 'q116', text: `¿Qué cosas jamás harían únicamente por dinero?` },
      { id: 'q117', text: `¿Qué tendría que suceder para que AMAREA fuera económicamente sostenible?` },
      { id: 'q118', text: `¿Qué tendría que suceder para que pudiera crecer sin depender de trabajo no remunerado de ustedes?` },
      { id: 'q119', text: `¿Qué significa para ti que AMAREA "tenga éxito"?` },
      { id: 'q120', text: `Si AMAREA generara mucho dinero, ¿qué cambiarías y qué no cambiarías?` }
    ]
  },
  {
    id: 'futuro',
    title: '7. CRECIMIENTO, ESCALA Y FUTURO',
    questions: [
      { id: 'q121', text: `¿Quieres que AMAREA crezca?` },
      { id: 'q122', text: `¿Qué significa crecer para ti?` },
      { id: 'q123', text: `¿Más eventos?` },
      { id: 'q124', text: `¿Eventos más grandes?` },
      { id: 'q125', text: `¿Mejores producciones?` },
      { id: 'q126', text: `¿Artistas internacionales?` },
      { id: 'q127', text: `¿Más ingresos?` },
      { id: 'q128', text: `¿Más reconocimiento?` },
      { id: 'q129', text: `¿Más ciudades?` },
      { id: 'q130', text: `¿Mayor impacto cultural?` },
      { id: 'q131', text: `¿Una empresa formal?` },
      { id: 'q132', text: `¿Una marca internacional?` },
      { id: 'q133', text: `¿Qué escala te parecería ideal?` },
      { id: 'q134', text: `¿Qué escala te parecería excesiva?` },
      { id: 'q135', text: `¿Qué no debería sacrificarse nunca para crecer?` },
      { id: 'q136', text: `¿Qué sí tendría que cambiar?` },
      { id: 'q137', text: `¿Cómo imaginas AMAREA dentro de tres años?` },
      { id: 'q138', text: `¿Cómo imaginas AMAREA dentro de diez años?` },
      { id: 'q139', text: `Si tuvieran recursos ilimitados durante un año, ¿qué construirían?` },
      { id: 'q140', text: `¿Qué parte de esa visión podría empezar a construirse con los recursos actuales?` }
    ]
  },
  {
    id: 'organizacion',
    title: '8. LOS CUATRO COMO ORGANIZACIÓN',
    questions: [
      { id: 'q141', text: `¿Qué aportas tú a AMAREA que los otros tres no aportan de la misma manera?` },
      { id: 'q142', text: `¿Qué aporta cada uno de los otros integrantes?` },
      { id: 'q143', text: `¿En qué consideras que eres particularmente bueno?` },
      { id: 'q144', text: `¿Qué actividades disfrutas hacer dentro de AMAREA?` },
      { id: 'q145', text: `¿Qué actividades no quieres hacer?` },
      { id: 'q146', text: `¿Qué haces actualmente que consideras que debería hacer otra persona?` },
      { id: 'q147', text: `¿Qué debería dejar de hacer AMAREA?` },
      { id: 'q148', text: `¿Qué debería empezar a hacer?` },
      { id: 'q149', text: `¿Qué debería hacer con mucha mayor frecuencia?` },
      { id: 'q150', text: `¿Cómo se toman actualmente las decisiones?` },
      { id: 'q151', text: `¿Qué funciona bien de esa forma?` },
      { id: 'q152', text: `¿Qué no funciona?` },
      { id: 'q153', text: `¿Qué sucede cuando existen opiniones diferentes entre ustedes?` },
      { id: 'q154', text: `¿Cómo debería resolverse una diferencia importante?` },
      { id: 'q155', text: `¿Qué decisiones deberían tomarse entre los cuatro?` },
      { id: 'q156', text: `¿Qué decisiones podrían delegarse?` },
      { id: 'q157', text: `¿Qué responsabilidades deberían estar claramente asignadas a una persona?` },
      { id: 'q158', text: `¿Qué información debería estar disponible para los cuatro?` },
      { id: 'q159', text: `¿Qué información o decisiones deberían permanecer bajo responsabilidad específica?` },
      { id: 'q160', text: `¿Qué tendría que cambiar internamente para que AMAREA pudiera crecer sin que la organización entre ustedes se convierta en un problema?` }
    ]
  },
  {
    id: 'final',
    title: 'PREGUNTA FINAL',
    questions: [
      { id: 'q161', text: `Si tuvieras que entregarle AMAREA a alguien que sabe construir empresas, marcas, organizaciones y sistemas, pero no sabe absolutamente nada sobre ustedes, ¿qué necesitarías que esa persona entendiera para no construir una AMAREA equivocada? Escribe todo lo que consideres necesario. No pienses en estructura. No pienses en términos empresariales. No pienses en lo que "debería" ser. Explica qué no podemos permitirnos perder.` }
    ]
  }
];
